
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Remove trailing slash on all URLs (except root)
[[redirects]]
  from = "/*/"
  to = ":splat"
  status = 301
  force = true
  conditions = {Path = {match = "^/.+/$"}}

# Fix duplicate recruitment.box paths
[[redirects]]
  from = "/recruitment.box/recruitment.box/*"
  to = "/recruitment.box/:splat"
  status = 301
  force = true

