
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add a redirect for paths without trailing slashes
[[redirects]]
  from = "/:ensNameOrAddress"
  to = "/:ensNameOrAddress/"
  status = 301
  force = true
