// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwrwedbfeommnskzzcgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3cndlZGJmZW9tbW5za3p6Y2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODU0MDksImV4cCI6MjA2NTI2MTQwOX0.Pr6tNHBKMFDQ9l30I1ZQbbtHmPc6-sOHGIcC59sfxUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);